import { useState } from "react";
import type { AuditRecord } from "../types/security";
import { RiskBadge } from "./RiskBadge";

interface Props { records: AuditRecord[]; loading: boolean; error: string | null; }

export function AuditPanel({ records, loading, error }: Props) {
  const [activeRecord, setActiveRecord] = useState<AuditRecord | null>(null);
  return <section className="panel audit-panel"><div className="panel-heading">审计记录 <span className="muted">{records.length}</span></div>{loading && <p className="muted">正在加载审计记录…</p>}{error && <div className="inline-error"><strong>审计加载失败</strong><br />{error}</div>}{!loading && !error && records.length === 0 && <p className="muted">提交请求后查看审计记录。</p>}{records.map(record => <div className="audit-record" key={record.task_id}><button onClick={() => setActiveRecord(record)}><span className="audit-title"><RiskBadge level={record.risk_level ?? undefined} /><strong title={record.case_title ?? record.tool}>{record.case_title ?? record.tool}</strong></span><span className="audit-status">{record.status}</span></button></div>)}{activeRecord && <div className="modal-backdrop" role="presentation" onClick={() => setActiveRecord(null)}><div className="audit-modal" role="dialog" aria-modal="true" aria-labelledby="audit-modal-title" onClick={event => event.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">AUDIT DETAIL</span><h2 id="audit-modal-title"><RiskBadge level={activeRecord.risk_level ?? undefined} /> <span className="modal-title-wrap">{activeRecord.case_title ?? activeRecord.tool}</span></h2></div><button className="modal-close" onClick={() => setActiveRecord(null)} aria-label="关闭">×</button></div><div className="modal-body"><p>task_id：<span className="mono">{activeRecord.task_id}</span></p><p>案例：{activeRecord.case_title ?? "未命名案例"}</p><p>来源：<span className="mono">{activeRecord.case_source ?? "—"}</span></p><p>用户：{activeRecord.user_id}</p><p>工具：{activeRecord.tool}</p><p>风险等级：{activeRecord.risk_level ?? "—"}</p><p>审批审计：{activeRecord.approval_audit_log.length} 条</p><h3>事件</h3><pre>{JSON.stringify(activeRecord.events, null, 2)}</pre><h3>审批审计日志</h3><pre>{JSON.stringify(activeRecord.approval_audit_log, null, 2)}</pre></div><div className="modal-footer"><button className="button secondary" onClick={() => setActiveRecord(null)}>关闭</button></div></div></div>}</section>;
}
